// constants

// AWS REGION
const AWS_REGION = 'ap-northeast-1';
// AWS PROFILE NAME
const AWS_PROFILE_NAME = 'private';
// AWS ECR REPOSITORY NAME
const AWS_ECR_REPOSITORY_NAME = 'myecr';
// APPLICATION ROOT PATH
const APP_PATH = './example/';
// FARGATE TASK DEFINITION TEMPLATE FILE PATH
const TASK_DEFINITION_TEMPLATE_FILE = `${APP_PATH}task-definition.json`;
// DEPLOY PARAMETER FILE PATH
const DEPLOY_ENV_FILE = `${APP_PATH}deploy_env.yaml`;
export {
  AWS_REGION,
  AWS_PROFILE_NAME,
  AWS_ECR_REPOSITORY_NAME,
  APP_PATH,
  TASK_DEFINITION_TEMPLATE_FILE,
  DEPLOY_ENV_FILE,
};
